name: Java CI/CD Pipeline (No Maven)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile source code
        run: |
          javac -cp "junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:." src/main/java/com/example/Calculator.java src/test/java/com/example/CalculatorTest.java -d classes
      - name: Run tests
        run: |
          java -cp "junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:classes" org.junit.runner.JUnitCore com.example.CalculatorTest
      - name: Package application
        run: |
          jar cf calculator-app.jar -C classes .
      - name: Deploy to remote server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP << 'EOF'
            cd /path/to/your/app
            git pull origin main
            mkdir -p classes
            javac -cp "junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:." src/main/java/com/example/Calculator.java src/test/java/com/example/CalculatorTest.java -d classes
            jar cf calculator-app.jar -C classes .
            java -cp ".:classes:junit-4.13.2.jar" com.example.Calculator
          EOF
